name: Android CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Manuel tetikleme ekledim

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    
    # Server App Build
    - name: Grant execute permission for server gradlew
      working-directory: ./server  # Server project path
      run: chmod +x gradlew
    
    - name: Build Server App
      working-directory: ./server  # Server project path  
      run: ./gradlew assembleDebug
    
    - name: Upload Server APK
      uses: actions/upload-artifact@v3
      with:
        name: server-app-debug
        path: ./server/app/build/outputs/apk/debug/app-debug.apk
    
    # Client App Build
    - name: Grant execute permission for client gradlew
      working-directory: ./client  # Client project path
      run: chmod +x gradlew
    
    - name: Build Client App
      working-directory: ./client  # Client project path
      run: ./gradlew assembleDebug
    
    - name: Upload Client APK
      uses: actions/upload-artifact@v3
      with:
        name: client-app-debug
        path: ./client/app/build/outputs/apk/debug/app-debug.apk
